# Generated by Django 6.0.1 on 2026-03-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_event_options_event_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Giving', 'Giving'), ('Programs', 'Programs'), ('Community', 'Community'), ('Events', 'Events'), ('Achievements', 'Achievements'), ('Scholarship', 'Scholarship')], default='Community', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
