# Generated by Django 6.0.1 on 2026-03-15 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_event_participants_internship_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('Student Aid', 'Student Aid'), ('Infrastructure', 'Infrastructure'), ('Research', 'Research'), ('Faculty', 'Faculty')], default='Student Aid', max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('donors_count', models.PositiveIntegerField(default=0)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('GCash', 'GCash'), ('Bank Transfer', 'Bank Transfer')], default='Credit Card', max_length=20)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='api.campaign')),
            ],
            options={
                'ordering': ['-donated_at'],
            },
        ),
    ]
