# Generated by Django 6.0.1 on 2026-04-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_experience_aligned_to_degree_experience_income_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='timeline_status',
            field=models.CharField(blank=True, default='Incoming', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='timeline_status',
            field=models.CharField(blank=True, default='Incoming', max_length=20),
        ),
        migrations.AddField(
            model_name='internship',
            name='timeline_status',
            field=models.CharField(blank=True, default='Incoming', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='timeline_status',
            field=models.CharField(blank=True, default='Incoming', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='timeline_status',
            field=models.CharField(blank=True, default='Incoming', max_length=20),
        ),
    ]
