# Generated by Django 6.0.1 on 2026-04-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_campaign_timeline_status_event_timeline_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='timeline_status',
            field=models.CharField(blank=True, default='Upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeline_status',
            field=models.CharField(blank=True, default='Upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='internship',
            name='timeline_status',
            field=models.CharField(blank=True, default='Upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='timeline_status',
            field=models.CharField(blank=True, default='Upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='timeline_status',
            field=models.CharField(blank=True, default='Upcoming', max_length=20),
        ),
    ]
